import { reportService } from "../../../services/report.service";
import { Card, CardContent, CardHeader, CardTitle } from "@janprashna/ui";
import { StatusBadge } from "../../../components/shared/StatusBadge";
import { EmptyState } from "../../../components/shared/EmptyState";
import Link from "next/link";

export default async function ReportDetailPage({ params }: { params: { id: string } }) {
  const report = await reportService.getReport(params.id);

  if (!report) {
    return (
      <EmptyState icon="📊" title="Report Not Found" description="This report does not exist."
        action={<Link href="/reports" className="text-primary font-ui text-sm hover:underline">Back to Reports</Link>}
      />
    );
  }

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex items-center gap-4">
        <Link href="/reports" className="text-muted-foreground hover:text-foreground font-ui text-sm">← Reports</Link>
      </div>

      <div className="border-l-4 border-primary pl-6 py-2">
        <p className="text-xs uppercase tracking-widest font-ui text-primary font-semibold mb-1">{report.report_type} Report</p>
        <h1 className="font-display text-3xl font-bold">{report.report_name}</h1>
        <p className="font-mono text-sm text-muted-foreground mt-1">{report.period_start} → {report.period_end}</p>
      </div>

      <div className="grid md:grid-cols-3 gap-4">
        {[
          { label: 'Questions Analyzed', value: report.total_questions.toLocaleString() },
          { label: 'Clusters Found', value: report.clusters_analyzed.toLocaleString() },
          { label: 'Generated By', value: report.generated_by },
        ].map(({ label, value }) => (
          <Card key={label} className="shadow-none border-border/60 bg-paper">
            <CardContent className="p-4">
              <p className="text-xs font-ui text-muted-foreground uppercase tracking-wide">{label}</p>
              <p className="font-display font-bold text-xl mt-1">{value}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {report.ai_summary && (
        <Card className="shadow-none border-border/60">
          <CardHeader className="border-b border-border/50 pb-4">
            <CardTitle className="font-display flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-primary inline-block"></span>
              AI Executive Summary
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-6">
            <p className="font-sans text-base leading-relaxed text-foreground">{report.ai_summary}</p>
          </CardContent>
        </Card>
      )}

      <div className="flex gap-3">
        {report.pdf_path && (
          <button className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-ui font-medium hover:bg-primary/90 transition-colors">
            Download PDF
          </button>
        )}
        {report.excel_path && (
          <button className="flex items-center gap-2 px-4 py-2 bg-paper border border-border rounded-lg text-sm font-ui font-medium hover:bg-background transition-colors">
            Download Excel
          </button>
        )}
      </div>
    </div>
  );
}
